### ISSUE TITLE
--prod build has with one or more "... is not a function" type runtime errors

### ISSUE THREAD

**Issue by runette** [runette/ngx-leaflet-fullscreen#1]
The library does not like being built with `"buildOptimizer": true`, doing so will result in runtime errors like this.

**Comment by serenadini** [comment]
Hello! thank you for this plugin. I'm experiencing this issue with the ng build--prod. I tried to set "buildOptimizer": false but, still, im facing those issues because the script is not served over https. 
The issue is "FAILED TO LOAD RESOURCE: net:: ERR_CERT_COMMON_NAME_INVALID. How can i fix this?

**Comment by runette** [comment]
Hi.

Can you open a new issue about this - since it appears to be a different
error message.

Also - I am not sure what you mean by "the script is not served over
HTTPS"? Can you explain further what you mean by that - which script are
you referring to?

**Comment by serenadini** [comment]
Hi, thanks for the answer!
It was a problem with my browser and i fixed it so i deleted the message. Thank you again for the plugin!
 

Da: "Paul" notifications@github.com
A: "runette/ngx-leaflet-fullscreen" ngx-leaflet-fullscreen@noreply.github.com
Cc: "serenadini" serena.dini@protom.com,"Comment" comment@noreply.github.com
Data: Tue, 04 Aug 2020 01:04:35 -0700
Oggetto: Re: [runette/ngx-leaflet-fullscreen] --prod build has with one or more "... is not a function" type runtime errors (#1)




Hi.





Can you open a new issue about this - since it appears to be a different


error message.





Also - I am not sure what you mean by "the script is not served over


HTTPS"? Can you explain further what you mean by that - which script are


you referring to?
