### ISSUE TITLE
Leaflet.fullScreen makes other plugins fail

### ISSUE THREAD

**Issue by bsoviedo** [runette/ngx-leaflet-fullscreen#5]
Hi @runette , 

Im working on Angular  11^ and when i load the application in my map.module.ts 

```
import {NgxLeafletFullscreenModule} from '@runette/ngx-leaflet-fullscreen'

imports: [
    ...
    NgxLeafletFullscreenModule,
  ],
```

my other plugins stop working,  in console just appear 

```
L.realtime is not a function
L.easyprint is not a function
```

Im working with leaflet.realtime and leaflet.easyPrint and both of them stop working with just charge the module in the imports modules. When i delete the import of  leaflet fullscreen,  plugins works normally.

any thougths?

**Comment by runette** [comment]
As explained in this article (see the section "Don't get caught in L") the method used in this extension does not use the `L.realtime` syntax.

You should be able to import the realtime and easyprint functions explicitly. Otherwise - you should be able to `import * as L from 'leaflet'` in your code to make it work,

**Comment by bsoviedo** [comment]
hey @runette !,

thanks for your prompt response,

I was able to fix the issue, i followed a little about the sintax you use in this plugin, but i used in the other plugins, also i declared some types for them and they worked pretty weel. 

Im closing the issue, 

thanks a lot
